import {
  ExerciseCategory,
  ExerciseDifficulty,
  LessonCategory,
  LessonType,
  Prisma,
  PrismaClient,
} from '@prisma/client';

const prisma = new PrismaClient();

const exerciseRules: Record<
  string,
  Array<{
    code: string;
    phase: string;
    joint: string;
    landmarks: Prisma.InputJsonObject;
    angleMin: number;
    angleMax: number;
    severity: string;
    feedback: string;
  }>
> = {
  squat: [
    {
      code: 'squat-knee-depth',
      phase: 'down',
      joint: 'knee',
      landmarks: { a: 23, vertex: 25, b: 27 },
      angleMin: 60,
      angleMax: 115,
      severity: 'warn',
      feedback: 'Lower with control and reach safe squat depth.',
    },
    {
      code: 'squat-back-control',
      phase: 'any',
      joint: 'hip',
      landmarks: { a: 11, vertex: 23, b: 25 },
      angleMin: 70,
      angleMax: 120,
      severity: 'error',
      feedback: 'Keep your chest lifted and avoid rounding your back.',
    },
  ],
  pushup: [
    {
      code: 'pushup-elbow-depth',
      phase: 'down',
      joint: 'elbow',
      landmarks: { a: 11, vertex: 13, b: 15 },
      angleMin: 65,
      angleMax: 105,
      severity: 'warn',
      feedback: 'Lower until the elbows bend enough without losing control.',
    },
    {
      code: 'pushup-body-line',
      phase: 'any',
      joint: 'body',
      landmarks: { a: 11, vertex: 23, b: 27 },
      angleMin: 155,
      angleMax: 185,
      severity: 'error',
      feedback: 'Keep shoulders, hips, and heels in one strong line.',
    },
  ],
  plank: [
    {
      code: 'plank-alignment',
      phase: 'hold',
      joint: 'body',
      landmarks: { a: 11, vertex: 23, b: 27 },
      angleMin: 160,
      angleMax: 185,
      severity: 'error',
      feedback: 'Keep your hips aligned with shoulders and heels.',
    },
  ],
  lunge: [
    {
      code: 'lunge-front-knee',
      phase: 'down',
      joint: 'knee',
      landmarks: { a: 23, vertex: 25, b: 27 },
      angleMin: 80,
      angleMax: 110,
      severity: 'warn',
      feedback: 'Bend the front knee with control and keep it tracking forward.',
    },
  ],
  'bicep-curl': [
    {
      code: 'curl-top-range',
      phase: 'up',
      joint: 'elbow',
      landmarks: { a: 11, vertex: 13, b: 15 },
      angleMin: 25,
      angleMax: 60,
      severity: 'warn',
      feedback: 'Curl fully without swinging your torso.',
    },
  ],
  'glute-bridge': [
    {
      code: 'bridge-hip-extension',
      phase: 'up',
      joint: 'hip',
      landmarks: { a: 11, vertex: 23, b: 25 },
      angleMin: 145,
      angleMax: 185,
      severity: 'warn',
      feedback: 'Lift hips until the body forms a strong bridge line.',
    },
  ],
  'mountain-climber': [
    {
      code: 'climber-hip-line',
      phase: 'any',
      joint: 'body',
      landmarks: { a: 11, vertex: 23, b: 27 },
      angleMin: 155,
      angleMax: 185,
      severity: 'error',
      feedback: 'Keep hips level and avoid bouncing.',
    },
  ],
  'shoulder-press': [
    {
      code: 'press-lockout',
      phase: 'up',
      joint: 'elbow',
      landmarks: { a: 11, vertex: 13, b: 15 },
      angleMin: 150,
      angleMax: 185,
      severity: 'warn',
      feedback: 'Press to a strong overhead position without arching.',
    },
  ],
  deadlift: [
    {
      code: 'deadlift-hip-hinge',
      phase: 'down',
      joint: 'hip',
      landmarks: { a: 11, vertex: 23, b: 25 },
      angleMin: 40,
      angleMax: 95,
      severity: 'warn',
      feedback: 'Hinge from the hips and keep the back braced.',
    },
  ],
  'jumping-jack': [
    {
      code: 'jack-arms-overhead',
      phase: 'up',
      joint: 'shoulder',
      landmarks: { a: 23, vertex: 11, b: 15 },
      angleMin: 130,
      angleMax: 185,
      severity: 'warn',
      feedback: 'Reach the arms overhead through a full range.',
    },
  ],
  'tricep-dip': [
    {
      code: 'dip-elbow-depth',
      phase: 'down',
      joint: 'elbow',
      landmarks: { a: 11, vertex: 13, b: 15 },
      angleMin: 75,
      angleMax: 115,
      severity: 'warn',
      feedback: 'Lower under control without dropping too deep.',
    },
  ],
  'calf-raise': [
    {
      code: 'calf-knee-stability',
      phase: 'any',
      joint: 'knee',
      landmarks: { a: 23, vertex: 25, b: 27 },
      angleMin: 155,
      angleMax: 185,
      severity: 'warn',
      feedback: 'Keep knees mostly straight and avoid bouncing.',
    },
  ],
  'side-lunge': [
    {
      code: 'side-lunge-knee-depth',
      phase: 'down',
      joint: 'knee',
      landmarks: { a: 23, vertex: 25, b: 27 },
      angleMin: 75,
      angleMax: 115,
      severity: 'warn',
      feedback: 'Sit into the working leg while keeping the knee aligned.',
    },
  ],
  superman: [
    {
      code: 'superman-extension-control',
      phase: 'up',
      joint: 'hip',
      landmarks: { a: 11, vertex: 23, b: 25 },
      angleMin: 150,
      angleMax: 185,
      severity: 'warn',
      feedback: 'Lift with control and avoid forcing the neck.',
    },
  ],
  burpee: [
    {
      code: 'burpee-plank-line',
      phase: 'down',
      joint: 'body',
      landmarks: { a: 11, vertex: 23, b: 27 },
      angleMin: 155,
      angleMax: 185,
      severity: 'error',
      feedback: 'Keep a strong plank position during the floor phase.',
    },
  ],
  'high-knees': [
    {
      code: 'high-knees-torso',
      phase: 'any',
      joint: 'torso',
      landmarks: { a: 11, vertex: 23, b: 25 },
      angleMin: 150,
      angleMax: 185,
      severity: 'warn',
      feedback: 'Stay tall and avoid leaning back.',
    },
  ],
  'lateral-raise': [
    {
      code: 'lateral-raise-height',
      phase: 'up',
      joint: 'shoulder',
      landmarks: { a: 23, vertex: 11, b: 15 },
      angleMin: 120,
      angleMax: 170,
      severity: 'warn',
      feedback: 'Raise to shoulder height without shrugging.',
    },
  ],
  'tricep-extension': [
    {
      code: 'tricep-extension-lockout',
      phase: 'up',
      joint: 'elbow',
      landmarks: { a: 11, vertex: 13, b: 15 },
      angleMin: 145,
      angleMax: 185,
      severity: 'warn',
      feedback: 'Extend the elbow fully while keeping the upper arm stable.',
    },
  ],
  'reverse-lunge': [
    {
      code: 'reverse-lunge-front-knee',
      phase: 'down',
      joint: 'knee',
      landmarks: { a: 23, vertex: 25, b: 27 },
      angleMin: 80,
      angleMax: 110,
      severity: 'warn',
      feedback: 'Keep the front knee aligned over the foot.',
    },
  ],
  'wall-sit': [
    {
      code: 'wall-sit-knee-angle',
      phase: 'hold',
      joint: 'knee',
      landmarks: { a: 23, vertex: 25, b: 27 },
      angleMin: 82,
      angleMax: 105,
      severity: 'warn',
      feedback: 'Hold a strong seated position with knees near 90 degrees.',
    },
  ],
};

const exercises = [
  {
    slug: 'squat',
    name: 'Squat',
    description: 'Lower-body strength exercise focused on quads, glutes, and core control.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 12,
    estimatedSeconds: 45,
    commonErrors: ['Knees collapsing inward', 'Rounded back', 'Insufficient depth'],
    modifications: ['Box squat', 'Goblet squat'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 100, up: 160 },
      rules: [
        {
          id: 'squat-knee-depth',
          landmarks: { a: 23, vertex: 25, b: 27 },
          phase: 'down',
          minAngle: 60,
          maxAngle: 115,
          severity: 'warn',
        },
      ],
    },
  },
  {
    slug: 'pushup',
    name: 'Push-up',
    description: 'Upper-body pushing exercise for chest, shoulders, triceps, and core stability.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['chest', 'shoulders', 'arms'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 10,
    estimatedSeconds: 40,
    commonErrors: ['Sagging hips', 'Short range of motion', 'Elbows flaring too wide'],
    modifications: ['Incline push-up', 'Knee push-up'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 13, b: 15 },
      repPhaseThreshold: { down: 100, up: 155 },
    },
  },
  {
    slug: 'plank',
    name: 'Plank',
    description: 'Static core hold for trunk stability and shoulder endurance.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders', 'glutes'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 1,
    estimatedSeconds: 60,
    commonErrors: ['Hips too high', 'Lower back sagging', 'Neck overextended'],
    modifications: ['Knee plank', 'Long-lever plank'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 23, b: 27 },
      repPhaseThreshold: { down: 100, up: 170 },
    },
  },
  {
    slug: 'lunge',
    name: 'Lunge',
    description: 'Single-leg strength movement for legs, glutes, balance, and coordination.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 10,
    estimatedSeconds: 45,
    commonErrors: ['Front knee drifting inward', 'Torso collapsing forward'],
    modifications: ['Reverse lunge', 'Assisted lunge'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 95, up: 160 },
    },
  },
  {
    slug: 'bicep-curl',
    name: 'Bicep Curl',
    description: 'Arm isolation exercise focused on elbow flexion and shoulder stability.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['arms'],
    secondaryMuscles: ['shoulders'],
    equipment: ['dumbbells'],
    sets: 3,
    reps: 12,
    estimatedSeconds: 40,
    commonErrors: ['Swinging torso', 'Incomplete range of motion'],
    modifications: ['Resistance band curl', 'Alternating curl'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 13, b: 15 },
      repPhaseThreshold: { down: 65, up: 140 },
    },
  },
  {
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    description: 'Hip extension exercise for glutes, hamstrings, and trunk control.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['core', 'legs'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 15,
    estimatedSeconds: 45,
    commonErrors: ['Low hip height', 'Overarching lower back'],
    modifications: ['Single-leg bridge', 'Paused bridge'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 23, b: 25 },
      repPhaseThreshold: { down: 100, up: 155 },
    },
  },
  {
    slug: 'mountain-climber',
    name: 'Mountain Climber',
    description: 'Dynamic full-body conditioning movement with core and shoulder demand.',
    category: ExerciseCategory.HIIT,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    primaryMuscles: ['core', 'fullbody'],
    secondaryMuscles: ['shoulders', 'legs'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 20,
    estimatedSeconds: 30,
    commonErrors: ['Hips bouncing', 'Rushing with poor control'],
    modifications: ['Slow mountain climber', 'Elevated mountain climber'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 80, up: 150 },
    },
  },
  {
    slug: 'shoulder-press',
    name: 'Shoulder Press',
    description: 'Vertical pressing movement for shoulders and triceps.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['arms', 'core'],
    equipment: ['dumbbells'],
    sets: 3,
    reps: 10,
    estimatedSeconds: 40,
    commonErrors: ['Overarching back', 'Incomplete lockout'],
    modifications: ['Seated press', 'Single-arm press'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 13, b: 15 },
      repPhaseThreshold: { down: 90, up: 155 },
    },
  },
  {
    slug: 'deadlift',
    name: 'Deadlift',
    description: 'Hip-hinge strength movement for posterior chain control and back position.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    primaryMuscles: ['back', 'glutes', 'legs'],
    secondaryMuscles: ['core', 'arms'],
    equipment: ['dumbbells'],
    sets: 3,
    reps: 8,
    estimatedSeconds: 50,
    commonErrors: ['Rounded back', 'Squatting instead of hinging'],
    modifications: ['Romanian deadlift', 'Kettlebell deadlift'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 23, b: 25 },
      repPhaseThreshold: { down: 60, up: 165 },
    },
  },
  {
    slug: 'jumping-jack',
    name: 'Jumping Jack',
    description: 'Low-skill cardio movement for full-body warmups and conditioning.',
    category: ExerciseCategory.CARDIO,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['fullbody'],
    secondaryMuscles: ['legs', 'shoulders'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 20,
    estimatedSeconds: 30,
    commonErrors: ['Arms not reaching overhead', 'Hard landings'],
    modifications: ['Step jack', 'Power jack'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 11, b: 15 },
      repPhaseThreshold: { down: 50, up: 140 },
    },
  },
  {
    slug: 'tricep-dip',
    name: 'Tricep Dip',
    description: 'Bodyweight arm exercise using elbow extension and shoulder control.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['arms'],
    secondaryMuscles: ['shoulders', 'chest'],
    equipment: ['chair'],
    sets: 3,
    reps: 12,
    estimatedSeconds: 35,
    commonErrors: ['Elbows flaring', 'Dropping too deep', 'Shoulders shrugging'],
    modifications: ['Bent-knee dip', 'Straight-leg dip'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 13, b: 15 },
      repPhaseThreshold: { down: 85, up: 155 },
    },
  },
  {
    slug: 'calf-raise',
    name: 'Calf Raise',
    description: 'Lower-leg strength exercise focused on ankle control and calf endurance.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['legs'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 20,
    estimatedSeconds: 30,
    commonErrors: ['Bent knees', 'Bouncing through reps'],
    modifications: ['Supported calf raise', 'Single-leg calf raise'],
    rulesConfig: {
      repAngleLandmarks: { a: 25, vertex: 27, b: 31 },
      repPhaseThreshold: { down: 100, up: 125 },
    },
  },
  {
    slug: 'side-lunge',
    name: 'Side Lunge',
    description: 'Lateral lower-body movement for hips, glutes, and single-leg control.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 10,
    estimatedSeconds: 40,
    commonErrors: ['Knee collapsing inward', 'Torso dropping', 'Shallow range'],
    modifications: ['Assisted side lunge', 'Cossack squat'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 95, up: 160 },
    },
  },
  {
    slug: 'superman',
    name: 'Superman',
    description: 'Back-extension floor exercise for posterior chain endurance.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['back', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 15,
    estimatedSeconds: 35,
    commonErrors: ['Neck overextension', 'No pause at the top', 'Too much range'],
    modifications: ['Alternating superman', 'Prone back extension'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 23, b: 25 },
      repPhaseThreshold: { down: 150, up: 168 },
    },
  },
  {
    slug: 'burpee',
    name: 'Burpee',
    description: 'Full-body conditioning exercise combining squat, plank, and jump patterns.',
    category: ExerciseCategory.HIIT,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    primaryMuscles: ['fullbody'],
    secondaryMuscles: ['core', 'legs', 'shoulders'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 10,
    estimatedSeconds: 30,
    commonErrors: ['Sagging plank', 'Soft jump', 'Rushing the movement'],
    modifications: ['Step-back burpee', 'Burpee without push-up'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 80, up: 155 },
    },
  },
  {
    slug: 'high-knees',
    name: 'High Knees',
    description: 'Cardio drill for hip flexors, rhythm, and upright posture.',
    category: ExerciseCategory.CARDIO,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['legs', 'core'],
    secondaryMuscles: ['fullbody'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 20,
    estimatedSeconds: 25,
    commonErrors: ['Low knee lift', 'Leaning back', 'Losing rhythm'],
    modifications: ['Marching high knees', 'Sprint high knees'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 75, up: 145 },
    },
  },
  {
    slug: 'lateral-raise',
    name: 'Lateral Raise',
    description: 'Shoulder isolation exercise for controlled arm elevation.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['arms'],
    equipment: ['dumbbells'],
    sets: 3,
    reps: 12,
    estimatedSeconds: 35,
    commonErrors: ['Raising too high', 'Shrugging shoulders', 'Swinging the body'],
    modifications: ['Band lateral raise', 'Seated lateral raise'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 11, b: 15 },
      repPhaseThreshold: { down: 60, up: 140 },
    },
  },
  {
    slug: 'tricep-extension',
    name: 'Tricep Extension',
    description: 'Arm isolation exercise focused on controlled elbow extension.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['arms'],
    secondaryMuscles: ['shoulders'],
    equipment: ['dumbbells'],
    sets: 3,
    reps: 12,
    estimatedSeconds: 35,
    commonErrors: ['Elbows drifting', 'Short range', 'Overarching back'],
    modifications: ['Band extension', 'Single-arm extension'],
    rulesConfig: {
      repAngleLandmarks: { a: 11, vertex: 13, b: 15 },
      repPhaseThreshold: { down: 85, up: 155 },
    },
  },
  {
    slug: 'reverse-lunge',
    name: 'Reverse Lunge',
    description: 'Single-leg lower-body exercise with easier balance than forward lunges.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 10,
    estimatedSeconds: 40,
    commonErrors: ['Front knee drifting inward', 'Torso leaning', 'Unstable step'],
    modifications: ['Supported reverse lunge', 'Deficit reverse lunge'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 95, up: 160 },
    },
  },
  {
    slug: 'wall-sit',
    name: 'Wall Sit',
    description: 'Static leg endurance hold for quads, glutes, and mental focus.',
    category: ExerciseCategory.STRENGTH,
    difficulty: ExerciseDifficulty.BEGINNER,
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    sets: 3,
    reps: 1,
    estimatedSeconds: 60,
    commonErrors: ['Hips too high', 'Heels lifting', 'Hands pushing on legs'],
    modifications: ['Higher wall sit', 'Weighted wall sit'],
    rulesConfig: {
      repAngleLandmarks: { a: 23, vertex: 25, b: 27 },
      repPhaseThreshold: { down: 100, up: 170 },
    },
  },
];

const programs = [
  {
    id: 'foundation-4w',
    name: 'Beginner Foundation',
    description: 'A 4-week starter plan to build consistency, basic strength, and safe form.',
    difficulty: ExerciseDifficulty.BEGINNER,
    durationWeeks: 4,
    sessionsPerWeek: 3,
    estimatedMinutesPerSession: 30,
    emoji: '🌱',
    goals: ['Build a consistent routine', 'Learn core movement patterns', 'Improve technique'],
    weeks: [
      {
        number: 1,
        theme: 'Foundation',
        days: [
          {
            id: 'w1d1',
            type: 'workout',
            exercises: [
              { exerciseId: 'squat', sets: 3, reps: 8, restSeconds: 60 },
              { exerciseId: 'pushup', sets: 3, reps: 5, restSeconds: 60 },
              { exerciseId: 'plank', sets: 3, reps: 1, restSeconds: 90 },
            ],
          },
          { id: 'w1d2', type: 'rest', exercises: [] },
          {
            id: 'w1d3',
            type: 'workout',
            exercises: [
              { exerciseId: 'lunge', sets: 3, reps: 8, restSeconds: 60 },
              { exerciseId: 'glute-bridge', sets: 3, reps: 12, restSeconds: 60 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'build-4w',
    name: 'Intermediate Build',
    description: 'A balanced strength program for users ready for higher weekly volume.',
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    durationWeeks: 4,
    sessionsPerWeek: 4,
    estimatedMinutesPerSession: 40,
    emoji: '⚡',
    goals: ['Increase training volume', 'Build strength endurance', 'Practice harder variations'],
    weeks: [
      {
        number: 1,
        theme: 'Build',
        days: [
          {
            id: 'w1d1',
            type: 'workout',
            exercises: [
              { exerciseId: 'squat', sets: 4, reps: 10, restSeconds: 60 },
              { exerciseId: 'glute-bridge', sets: 3, reps: 12, restSeconds: 60 },
            ],
          },
          {
            id: 'w1d2',
            type: 'workout',
            exercises: [
              { exerciseId: 'pushup', sets: 4, reps: 10, restSeconds: 60 },
              { exerciseId: 'shoulder-press', sets: 4, reps: 10, restSeconds: 60 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'athlete-4w',
    name: 'Advanced Athlete',
    description: 'A challenging 4-week plan for conditioning, strength, and high output.',
    difficulty: ExerciseDifficulty.ADVANCED,
    durationWeeks: 4,
    sessionsPerWeek: 5,
    estimatedMinutesPerSession: 50,
    emoji: '🏆',
    goals: ['Increase output', 'Combine strength and HIIT', 'Build advanced consistency'],
    weeks: [
      {
        number: 1,
        theme: 'Peak',
        days: [
          {
            id: 'w1d1',
            type: 'workout',
            exercises: [
              { exerciseId: 'squat', sets: 5, reps: 15, restSeconds: 60 },
              { exerciseId: 'lunge', sets: 4, reps: 12, restSeconds: 60 },
            ],
          },
          {
            id: 'w1d2',
            type: 'workout',
            exercises: [
              { exerciseId: 'mountain-climber', sets: 4, reps: 20, restSeconds: 45 },
              { exerciseId: 'pushup', sets: 5, reps: 15, restSeconds: 60 },
            ],
          },
        ],
      },
    ],
  },
];

const lessons = [
  {
    id: 'squat-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🦵',
    title: 'Squat technique basics',
    summary: 'Learn the key checkpoints for a safer, stronger squat.',
    body: [
      'Set your feet around shoulder width and keep pressure through the middle of the foot.',
      'Control the descent, keep the chest proud, and stand tall with the hips and knees together.',
    ],
    keyTakeaways: ['Brace before you descend', 'Track knees with toes', 'Use full controlled range'],
    durationMinutes: 8,
    youtubeVideoId: 'aclHkVaku9U',
    linkedExerciseId: 'squat',
    order: 1,
  },
  {
    id: 'pushup-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '💪',
    title: 'Push-up form guide',
    summary: 'Build a clean push-up with stable shoulders and a strong plank line.',
    body: [
      'Start from a strong plank and keep the ribs, hips, and head moving as one line.',
      'Lower under control, then press the floor away without shrugging the shoulders.',
    ],
    keyTakeaways: ['Keep a plank line', 'Control elbow angle', 'Use an easier variation when needed'],
    durationMinutes: 6,
    youtubeVideoId: 'IODxDxX7oi4',
    linkedExerciseId: 'pushup',
    order: 2,
  },
  {
    id: 'plank-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🧘',
    title: 'Plank alignment',
    summary: 'Understand the body position that makes a plank effective.',
    body: [
      'Stack shoulders over elbows and keep a straight line from head to heels.',
      'Squeeze glutes lightly and breathe steadily instead of holding your breath.',
    ],
    keyTakeaways: ['Avoid sagging hips', 'Breathe continuously', 'Quality beats duration'],
    durationMinutes: 5,
    youtubeVideoId: 'pSHjTRCQxIw',
    linkedExerciseId: 'plank',
    order: 3,
  },
  {
    id: 'lunge-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🏃',
    title: 'Lunge technique guide',
    summary: 'Learn how to keep balance, knee position, and torso control during lunges.',
    body: [
      'Start tall, step with control, and keep the front foot planted firmly on the floor.',
      'Lower until both knees bend comfortably, then drive through the front foot to return.',
    ],
    keyTakeaways: [
      'Keep the front knee tracking with the toes',
      'Stay tall through the torso',
      'Use a reverse lunge if balance is difficult',
    ],
    durationMinutes: 7,
    youtubeVideoId: 'QOVaHwm-Q6U',
    linkedExerciseId: 'lunge',
    order: 4,
  },
  {
    id: 'deadlift-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🏋️',
    title: 'Deadlift setup and hinge mechanics',
    summary: 'Practice the hip-hinge setup that keeps the bar path efficient and the back braced.',
    body: [
      'A deadlift starts with the bar close, a strong brace, and the hips set for a hinge rather than a squat.',
      'Push the floor away while keeping the back position stable and the arms long.',
    ],
    keyTakeaways: [
      'Keep the bar close',
      'Brace before the pull',
      'Hinge from the hips',
      'Finish tall without leaning back',
    ],
    durationMinutes: 6,
    youtubeVideoId: 'wYREQkVtvEc',
    linkedExerciseId: 'deadlift',
    order: 5,
  },
  {
    id: 'glute-bridge-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🍑',
    title: 'Glute bridge the right way',
    summary: 'Use the glutes instead of the lower back by controlling pelvis and hip position.',
    body: [
      'Lie down with knees bent, feet planted, and ribs controlled before lifting the hips.',
      'Pause at the top, squeeze the glutes, and avoid arching through the lower back.',
    ],
    keyTakeaways: [
      'Drive through the heels',
      'Pause at the top',
      'Avoid overextending the lower back',
    ],
    durationMinutes: 5,
    youtubeVideoId: 'wPM8icPu6H8',
    linkedExerciseId: 'glute-bridge',
    order: 6,
  },
  {
    id: 'jumping-jack-video',
    type: LessonType.VIDEO,
    category: LessonCategory.BEGINNER,
    emoji: '🤸',
    title: 'Jumping jack basics',
    summary: 'Learn a simple cardio movement with controlled arms, soft landings, and rhythm.',
    body: [
      'Start with feet together and arms relaxed, then jump out while the arms travel overhead.',
      'Land softly, keep breathing steady, and use step jacks when impact needs to be lower.',
    ],
    keyTakeaways: ['Land softly', 'Move arms through full range', 'Keep a steady rhythm'],
    durationMinutes: 3,
    youtubeVideoId: 'c4DAnQ6DtF8',
    linkedExerciseId: 'jumping-jack',
    order: 7,
  },
  {
    id: 'mountain-climber-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '⛰️',
    title: 'Mountain climber form',
    summary: 'Keep a strong plank line while driving the knees with control.',
    body: [
      'Set up in a plank with shoulders stacked over hands and hips level.',
      'Drive one knee at a time without letting the hips bounce or the lower back sag.',
    ],
    keyTakeaways: ['Hold a plank line', 'Keep shoulders stable', 'Choose control before speed'],
    durationMinutes: 4,
    youtubeVideoId: 'cnyTQDSE884',
    linkedExerciseId: 'mountain-climber',
    order: 8,
  },
  {
    id: 'burpee-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TRAINING,
    emoji: '💥',
    title: 'Burpee beginner progression',
    summary: 'Break the burpee into simple pieces so conditioning does not destroy technique.',
    body: [
      'Step or jump back into a plank, return the feet under the body, and finish with a controlled stand or jump.',
      'Beginners can remove the push-up or step the feet back to reduce impact.',
    ],
    keyTakeaways: ['Control the plank', 'Scale the impact', 'Keep reps smooth instead of rushed'],
    durationMinutes: 5,
    youtubeVideoId: 'dZgVxmf6jkA',
    linkedExerciseId: 'burpee',
    order: 9,
  },
  {
    id: 'high-knees-video',
    type: LessonType.VIDEO,
    category: LessonCategory.BEGINNER,
    emoji: '🏃',
    title: 'High knees drill',
    summary: 'Improve warmups and cardio rhythm with upright posture and active knee drive.',
    body: [
      'Stand tall, brace lightly, and drive the knees up without leaning back.',
      'Start with marching high knees, then increase tempo when control feels easy.',
    ],
    keyTakeaways: ['Stay upright', 'Drive knees actively', 'Start slow before adding speed'],
    durationMinutes: 3,
    youtubeVideoId: 'oDdkytliOqE',
    linkedExerciseId: 'high-knees',
    order: 10,
  },
  {
    id: 'lateral-raise-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🙆',
    title: 'Lateral raise shoulder control',
    summary: 'Learn how to raise the arms without shrugging, swinging, or overloading the neck.',
    body: [
      'Start with light weight, soft elbows, and shoulders relaxed away from the ears.',
      'Raise the arms under control to around shoulder height, then lower slowly without using momentum.',
    ],
    keyTakeaways: ['Use light weight', 'Avoid shrugging', 'Control the lowering phase'],
    durationMinutes: 4,
    youtubeVideoId: null,
    linkedExerciseId: 'lateral-raise',
    order: 11,
  },
  {
    id: 'tricep-dip-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🪑',
    title: 'Tricep dip setup',
    summary: 'Build safer dips by controlling shoulder position, elbow path, and range.',
    body: [
      'Set the hands firmly on a stable surface and keep the chest open before lowering.',
      'Bend the elbows under control and stop before the shoulders roll forward.',
    ],
    keyTakeaways: ['Keep elbows close', 'Do not drop too deep', 'Use bent knees to scale'],
    durationMinutes: 4,
    youtubeVideoId: null,
    linkedExerciseId: 'tricep-dip',
    order: 12,
  },
  {
    id: 'calf-raise-video',
    type: LessonType.VIDEO,
    category: LessonCategory.BEGINNER,
    emoji: '🦵',
    title: 'Calf raise tempo',
    summary: 'Use pauses and controlled range instead of bouncing through calf raises.',
    body: [
      'Stand tall, rise onto the balls of the feet, and pause at the top.',
      'Lower slowly until the heels return with control, keeping the knees mostly straight.',
    ],
    keyTakeaways: ['Pause at the top', 'Avoid bouncing', 'Use support for balance'],
    durationMinutes: 3,
    youtubeVideoId: null,
    linkedExerciseId: 'calf-raise',
    order: 13,
  },
  {
    id: 'reverse-lunge-video',
    type: LessonType.VIDEO,
    category: LessonCategory.TECHNIQUE,
    emoji: '🦶',
    title: 'Reverse lunge balance',
    summary: 'Practice a beginner-friendly lunge variation with better balance and knee control.',
    body: [
      'Step back softly, keep the front foot planted, and lower with the torso tall.',
      'Push through the front foot to return, keeping the knee aligned with the toes.',
    ],
    keyTakeaways: ['Step back with control', 'Keep the front knee aligned', 'Stay tall'],
    durationMinutes: 5,
    youtubeVideoId: null,
    linkedExerciseId: 'reverse-lunge',
    order: 14,
  },
  {
    id: 'wall-sit-video',
    type: LessonType.VIDEO,
    category: LessonCategory.BEGINNER,
    emoji: '🧱',
    title: 'Wall sit alignment',
    summary: 'Set up the wall sit so the legs work hard without stressing the knees unnecessarily.',
    body: [
      'Place the back against the wall and walk the feet forward until the knees stack over the ankles.',
      'Hold steady, breathe, and keep the hands off the thighs so the legs do the work.',
    ],
    keyTakeaways: ['Knees over ankles', 'Back against the wall', 'Breathe through the hold'],
    durationMinutes: 3,
    youtubeVideoId: null,
    linkedExerciseId: 'wall-sit',
    order: 15,
  },
  {
    id: 'form-over-reps',
    type: LessonType.ARTICLE,
    category: LessonCategory.TECHNIQUE,
    emoji: '🎯',
    title: 'Why form matters more than reps',
    summary: 'Better movement quality gives you safer progress and more useful training data.',
    body: [
      'A rep only counts when it trains the pattern you actually want. Rushing through sloppy reps can reinforce bad mechanics.',
      'Use the technique score as a guide: slow down, reduce range, or choose an easier variation when quality drops.',
      'Consistency with good form compounds faster than chasing high numbers with poor control.',
    ],
    readMinutes: 3,
    order: 16,
  },
  {
    id: 'progressive-overload',
    type: LessonType.ARTICLE,
    category: LessonCategory.TRAINING,
    emoji: '📈',
    title: 'Progressive overload without overdoing it',
    summary: 'Increase reps, sets, difficulty, or control gradually so your body can adapt.',
    body: [
      'Progressive overload means giving the body a little more challenge over time.',
      'For beginners, the best first overload is often better consistency and cleaner technique.',
      'Only increase one variable at a time: reps, sets, tempo, rest, or exercise difficulty.',
    ],
    readMinutes: 4,
    order: 17,
  },
  {
    id: 'rest-days',
    type: LessonType.ARTICLE,
    category: LessonCategory.RECOVERY,
    emoji: '😴',
    title: 'Why rest days improve progress',
    summary: 'Recovery is where your body adapts to the work you did.',
    body: [
      'Training creates stress. Recovery gives your body time to repair, adapt, and come back stronger.',
      'If soreness, sleep, or technique gets worse, take an easier day instead of forcing intensity.',
      'Good programs include rest because adaptation needs both stimulus and recovery.',
    ],
    readMinutes: 3,
    order: 18,
  },
  {
    id: 'warmup-cooldown',
    type: LessonType.ARTICLE,
    category: LessonCategory.TRAINING,
    emoji: '🌡️',
    title: 'Warm-up and cool-down basics',
    summary: 'Prepare the body before training and downshift after the session.',
    body: [
      'A warm-up should gradually raise temperature, increase joint range, and rehearse the movement patterns ahead.',
      'Use simple drills such as marching, arm circles, bodyweight squats, and light mobility before harder work.',
      'After training, slow breathing and easy movement help the body return to a calmer state.',
    ],
    readMinutes: 3,
    order: 19,
  },
  {
    id: 'sets-and-reps',
    type: LessonType.ARTICLE,
    category: LessonCategory.TRAINING,
    emoji: '🔢',
    title: 'How to choose sets and reps',
    summary: 'Understand the difference between practice, strength, endurance, and conditioning work.',
    body: [
      'Beginners usually progress best with moderate sets and clean reps instead of training to failure.',
      'Higher reps can build endurance, while lower reps with harder variations can build strength.',
      'When technique score drops, stop the set or switch to an easier modification.',
    ],
    readMinutes: 4,
    order: 20,
  },
  {
    id: 'sleep-muscle',
    type: LessonType.ARTICLE,
    category: LessonCategory.RECOVERY,
    emoji: '🌙',
    title: 'Sleep and muscle recovery',
    summary: 'Recovery quality depends heavily on sleep, stress, and consistency.',
    body: [
      'Sleep is when much of the repair and adaptation from training happens.',
      'If sleep is poor, keep the next workout easier and focus on technique quality.',
      'A stable bedtime routine often improves training progress more than adding extra exercises.',
    ],
    readMinutes: 3,
    order: 21,
  },
  {
    id: 'managing-doms',
    type: LessonType.ARTICLE,
    category: LessonCategory.RECOVERY,
    emoji: '🩹',
    title: 'Managing post-workout soreness',
    summary: 'Learn the difference between normal soreness and signs that you should back off.',
    body: [
      'Delayed onset muscle soreness is common after new exercises or higher volume.',
      'Light movement, hydration, sleep, and gradual progression usually help more than complete inactivity.',
      'Sharp pain, joint pain, or worsening technique is a signal to reduce intensity and seek guidance if needed.',
    ],
    readMinutes: 4,
    order: 22,
  },
  {
    id: 'starting-fitness',
    type: LessonType.ARTICLE,
    category: LessonCategory.BEGINNER,
    emoji: '🚀',
    title: 'How to start training safely',
    summary: 'Build a realistic routine that you can repeat without burning out.',
    body: [
      'Start with fewer sessions than you think you can handle and make them easy to repeat.',
      'Prioritize exercises you can perform with a strong technique score.',
      'Consistency for four weeks matters more than one perfect intense workout.',
    ],
    readMinutes: 4,
    order: 23,
  },
  {
    id: 'breathing-bracing',
    type: LessonType.ARTICLE,
    category: LessonCategory.TECHNIQUE,
    emoji: '🫁',
    title: 'Breathing and bracing',
    summary: 'Use breathing to keep the trunk stable without holding unnecessary tension.',
    body: [
      'Before a rep, take a calm breath and create light pressure around the torso.',
      'Keep the ribs stacked over the pelvis instead of flaring the chest upward.',
      'For longer holds, breathe steadily while maintaining the same body position.',
    ],
    readMinutes: 3,
    order: 24,
  },
  {
    id: 'injury-aware-training',
    type: LessonType.ARTICLE,
    category: LessonCategory.BEGINNER,
    emoji: '🛡️',
    title: 'Training with limitations',
    summary: 'Adapt exercise selection when joints, previous injuries, or fatigue need extra care.',
    body: [
      'Limitations do not always mean stopping training; often they mean choosing a safer variation.',
      'Use pain-free range, slower tempo, and easier modifications when technique starts to break down.',
      'If symptoms are sharp, persistent, or worsening, pause and get professional guidance.',
    ],
    readMinutes: 4,
    order: 25,
  },
];

async function main() {
  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { slug: exercise.slug },
      create: exercise,
      update: exercise,
    });
  }

  for (const [exerciseSlug, rules] of Object.entries(exerciseRules)) {
    const exercise = await prisma.exercise.findUnique({
      where: { slug: exerciseSlug },
      select: { id: true },
    });
    if (!exercise) continue;

    await prisma.exerciseRule.deleteMany({ where: { exerciseId: exercise.id } });
    await prisma.exerciseRule.createMany({
      data: rules.map((rule, index) => ({
        ...rule,
        exerciseId: exercise.id,
        order: index + 1,
      })),
    });
  }

  for (const program of programs) {
    await prisma.program.upsert({
      where: { id: program.id },
      create: program,
      update: program,
    });
  }

  for (const lesson of lessons) {
    await prisma.lesson.upsert({
      where: { id: lesson.id },
      create: lesson,
      update: lesson,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async error => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
