import type { Exercise } from '@/features/exercises/types';

export const EXERCISES: Exercise[] = [
  {
    id: 'squat',
    slug: 'squat',
    nameKey: 'exercises.squat.name',
    descriptionKey: 'exercises.squat.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '🏋️',
    repLandmark: 25,
    repPhaseThreshold: { down: 100, up: 160 },
    sets: 3,
    reps: 12,
    estimatedDuration: 45,
    commonErrorKeys: [
      'exercises.squat.errors.knees',
      'exercises.squat.errors.back',
      'exercises.squat.errors.depth',
    ],
    modificationKeys: ['exercises.squat.mods.easier', 'exercises.squat.mods.harder'],
    rules: [
      {
        id: 'squat-knee-depth',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'down',
        minAngle: 60,
        maxAngle: 115,
        feedbackKey: 'workout.feedback.squat.depth',
        severity: 'warn',
      },
      {
        id: 'squat-back',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'any',
        minAngle: 70,
        maxAngle: 110,
        feedbackKey: 'workout.feedback.squat.back',
        severity: 'error',
      },
    ],
  },
  {
    id: 'pushup',
    slug: 'pushup',
    nameKey: 'exercises.pushup.name',
    descriptionKey: 'exercises.pushup.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['chest', 'shoulders', 'arms'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '💪',
    repLandmark: 13,
    repPhaseThreshold: { down: 100, up: 155 },
    sets: 3,
    reps: 10,
    estimatedDuration: 40,
    commonErrorKeys: [
      'exercises.pushup.errors.hips',
      'exercises.pushup.errors.elbows',
      'exercises.pushup.errors.range',
    ],
    modificationKeys: ['exercises.pushup.mods.easier', 'exercises.pushup.mods.harder'],
    rules: [
      {
        id: 'pushup-elbow',
        landmarks: { a: 11, vertex: 13, b: 15 },
        phase: 'down',
        minAngle: 65,
        maxAngle: 100,
        feedbackKey: 'workout.feedback.pushup.elbow',
        severity: 'warn',
      },
      {
        id: 'pushup-body',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'any',
        minAngle: 160,
        maxAngle: 180,
        feedbackKey: 'workout.feedback.pushup.body',
        severity: 'error',
      },
    ],
  },
  {
    id: 'plank',
    slug: 'plank',
    nameKey: 'exercises.plank.name',
    descriptionKey: 'exercises.plank.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders', 'glutes'],
    thumbnailEmoji: '🧘',
    repLandmark: 23,
    repPhaseThreshold: { down: 100, up: 170 },
    sets: 3,
    reps: 1,
    estimatedDuration: 60,
    commonErrorKeys: ['exercises.plank.errors.hips', 'exercises.plank.errors.neck'],
    modificationKeys: ['exercises.plank.mods.easier', 'exercises.plank.mods.harder'],
    rules: [
      {
        id: 'plank-alignment',
        landmarks: { a: 11, vertex: 23, b: 27 },
        phase: 'hold',
        minAngle: 160,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.plank.alignment',
        severity: 'error',
      },
    ],
  },
  {
    id: 'lunge',
    slug: 'lunge',
    nameKey: 'exercises.lunge.name',
    descriptionKey: 'exercises.lunge.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '🦵',
    repLandmark: 25,
    repPhaseThreshold: { down: 95, up: 160 },
    sets: 3,
    reps: 10,
    estimatedDuration: 45,
    commonErrorKeys: ['exercises.lunge.errors.knee', 'exercises.lunge.errors.torso'],
    modificationKeys: ['exercises.lunge.mods.easier', 'exercises.lunge.mods.harder'],
    rules: [
      {
        id: 'lunge-front-knee',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'down',
        minAngle: 80,
        maxAngle: 105,
        feedbackKey: 'workout.feedback.lunge.knee',
        severity: 'warn',
      },
    ],
  },
  {
    id: 'shoulder-press',
    slug: 'shoulder-press',
    nameKey: 'exercises.shoulderPress.name',
    descriptionKey: 'exercises.shoulderPress.description',
    category: 'strength',
    difficulty: 'intermediate',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['arms', 'core'],
    thumbnailEmoji: '🏅',
    repLandmark: 13,
    repPhaseThreshold: { down: 90, up: 155 },
    sets: 3,
    reps: 10,
    estimatedDuration: 40,
    commonErrorKeys: [
      'exercises.shoulderPress.errors.arch',
      'exercises.shoulderPress.errors.lockout',
    ],
    modificationKeys: [
      'exercises.shoulderPress.mods.easier',
      'exercises.shoulderPress.mods.harder',
    ],
    rules: [
      {
        id: 'press-lockout',
        landmarks: { a: 11, vertex: 13, b: 15 },
        phase: 'up',
        minAngle: 150,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.press.lockout',
        severity: 'warn',
      },
    ],
  },
  {
    id: 'bicep-curl',
    slug: 'bicep-curl',
    nameKey: 'exercises.bicepCurl.name',
    descriptionKey: 'exercises.bicepCurl.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['arms'],
    secondaryMuscles: ['shoulders'],
    thumbnailEmoji: '💪',
    repLandmark: 13,
    repPhaseThreshold: { down: 150, up: 45 },
    sets: 3,
    reps: 12,
    estimatedDuration: 40,
    commonErrorKeys: ['exercises.bicepCurl.errors.swing', 'exercises.bicepCurl.errors.range'],
    modificationKeys: ['exercises.bicepCurl.mods.easier', 'exercises.bicepCurl.mods.harder'],
    rules: [
      {
        id: 'curl-top',
        landmarks: { a: 11, vertex: 13, b: 15 },
        phase: 'up',
        minAngle: 25,
        maxAngle: 55,
        feedbackKey: 'workout.feedback.curl.top',
        severity: 'warn',
      },
    ],
  },
  {
    id: 'glute-bridge',
    slug: 'glute-bridge',
    nameKey: 'exercises.gluteBridge.name',
    descriptionKey: 'exercises.gluteBridge.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['core', 'legs'],
    thumbnailEmoji: '🍑',
    repLandmark: 23,
    repPhaseThreshold: { down: 100, up: 155 },
    sets: 3,
    reps: 15,
    estimatedDuration: 45,
    commonErrorKeys: [
      'exercises.gluteBridge.errors.height',
      'exercises.gluteBridge.errors.squeeze',
    ],
    modificationKeys: ['exercises.gluteBridge.mods.easier', 'exercises.gluteBridge.mods.harder'],
    rules: [
      {
        id: 'bridge-hip',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'up',
        minAngle: 145,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.bridge.hip',
        severity: 'warn',
      },
    ],
  },
  {
    id: 'mountain-climber',
    slug: 'mountain-climber',
    nameKey: 'exercises.mountainClimber.name',
    descriptionKey: 'exercises.mountainClimber.description',
    category: 'hiit',
    difficulty: 'intermediate',
    primaryMuscles: ['core', 'fullbody'],
    secondaryMuscles: ['shoulders', 'legs'],
    thumbnailEmoji: '⛰️',
    repLandmark: 25,
    repPhaseThreshold: { down: 80, up: 150 },
    sets: 3,
    reps: 20,
    estimatedDuration: 30,
    commonErrorKeys: [
      'exercises.mountainClimber.errors.hips',
      'exercises.mountainClimber.errors.pace',
    ],
    modificationKeys: [
      'exercises.mountainClimber.mods.easier',
      'exercises.mountainClimber.mods.harder',
    ],
    rules: [
      {
        id: 'climber-hips',
        landmarks: { a: 11, vertex: 23, b: 27 },
        phase: 'any',
        minAngle: 160,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.climber.hips',
        severity: 'error',
      },
    ],
  },
  {
    id: 'deadlift',
    slug: 'deadlift',
    nameKey: 'exercises.deadlift.name',
    descriptionKey: 'exercises.deadlift.description',
    category: 'strength',
    difficulty: 'intermediate',
    primaryMuscles: ['back', 'glutes', 'legs'],
    secondaryMuscles: ['core', 'arms'],
    thumbnailEmoji: '🏋️',
    repLandmark: 23,
    repPhaseThreshold: { down: 60, up: 165 },
    sets: 3,
    reps: 8,
    estimatedDuration: 50,
    commonErrorKeys: ['exercises.deadlift.errors.back', 'exercises.deadlift.errors.hinge'],
    modificationKeys: ['exercises.deadlift.mods.easier', 'exercises.deadlift.mods.harder'],
    rules: [
      {
        id: 'deadlift-hinge',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'down',
        minAngle: 40,
        maxAngle: 90,
        feedbackKey: 'workout.feedback.deadlift.hinge',
        severity: 'warn',
      },
    ],
  },
  {
    id: 'jumping-jack',
    slug: 'jumping-jack',
    nameKey: 'exercises.jumpingJack.name',
    descriptionKey: 'exercises.jumpingJack.description',
    category: 'cardio',
    difficulty: 'beginner',
    primaryMuscles: ['fullbody'],
    secondaryMuscles: ['legs', 'shoulders'],
    thumbnailEmoji: '🤸',
    repLandmark: 15,
    repPhaseThreshold: { down: 50, up: 140 },
    sets: 3,
    reps: 20,
    estimatedDuration: 30,
    commonErrorKeys: ['exercises.jumpingJack.errors.arms', 'exercises.jumpingJack.errors.landing'],
    modificationKeys: ['exercises.jumpingJack.mods.easier', 'exercises.jumpingJack.mods.harder'],
    rules: [
      {
        id: 'jj-arms-up',
        landmarks: { a: 23, vertex: 11, b: 15 },
        phase: 'up',
        minAngle: 130,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.jumpingJack.arms',
        severity: 'warn',
      },
    ],
  },

  // ─── 11–20: new exercises ─────────────────────────────────────────────────

  {
    id: 'tricep-dip',
    slug: 'tricep-dip',
    nameKey: 'exercises.tricepDip.name',
    descriptionKey: 'exercises.tricepDip.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['arms'],
    secondaryMuscles: ['shoulders', 'chest'],
    thumbnailEmoji: '🪑',
    repLandmark: 13,
    repPhaseThreshold: { down: 85, up: 155 },
    sets: 3,
    reps: 12,
    estimatedDuration: 35,
    commonErrorKeys: [
      'exercises.tricepDip.errors.flare',
      'exercises.tricepDip.errors.depth',
      'exercises.tricepDip.errors.shrug',
    ],
    modificationKeys: ['exercises.tricepDip.mods.easier', 'exercises.tricepDip.mods.harder'],
    rules: [
      {
        id: 'tricep-dip-down',
        landmarks: { a: 11, vertex: 13, b: 15 },
        phase: 'down',
        minAngle: 75,
        maxAngle: 110,
        feedbackKey: 'workout.feedback.tricepDip.elbow',
        severity: 'warn',
      },
      {
        id: 'tricep-dip-up',
        landmarks: { a: 11, vertex: 13, b: 15 },
        phase: 'up',
        minAngle: 150,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.tricepDip.extension',
        severity: 'warn',
      },
    ],
  },

  {
    id: 'calf-raise',
    slug: 'calf-raise',
    nameKey: 'exercises.calfRaise.name',
    descriptionKey: 'exercises.calfRaise.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['legs'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '🦵',
    repLandmark: 25,
    repPhaseThreshold: { down: 165, up: 175 },
    sets: 3,
    reps: 20,
    estimatedDuration: 30,
    commonErrorKeys: ['exercises.calfRaise.errors.knee', 'exercises.calfRaise.errors.bounce'],
    modificationKeys: ['exercises.calfRaise.mods.easier', 'exercises.calfRaise.mods.harder'],
    rules: [
      {
        id: 'calf-raise-knee',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'any',
        minAngle: 165,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.calfRaise.knee',
        severity: 'warn',
      },
    ],
  },

  {
    id: 'side-lunge',
    slug: 'side-lunge',
    nameKey: 'exercises.sideLunge.name',
    descriptionKey: 'exercises.sideLunge.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '🦵',
    repLandmark: 25,
    repPhaseThreshold: { down: 95, up: 160 },
    sets: 3,
    reps: 10,
    estimatedDuration: 40,
    commonErrorKeys: [
      'exercises.sideLunge.errors.knee',
      'exercises.sideLunge.errors.torso',
      'exercises.sideLunge.errors.depth',
    ],
    modificationKeys: ['exercises.sideLunge.mods.easier', 'exercises.sideLunge.mods.harder'],
    rules: [
      {
        id: 'side-lunge-knee',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'down',
        minAngle: 75,
        maxAngle: 110,
        feedbackKey: 'workout.feedback.sideLunge.knee',
        severity: 'warn',
      },
    ],
  },

  {
    id: 'superman',
    slug: 'superman',
    nameKey: 'exercises.superman.name',
    descriptionKey: 'exercises.superman.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['back', 'glutes'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '🦸',
    repLandmark: 23,
    repPhaseThreshold: { down: 150, up: 168 },
    sets: 3,
    reps: 15,
    estimatedDuration: 35,
    commonErrorKeys: [
      'exercises.superman.errors.neck',
      'exercises.superman.errors.hold',
      'exercises.superman.errors.range',
    ],
    modificationKeys: ['exercises.superman.mods.easier', 'exercises.superman.mods.harder'],
    rules: [
      {
        id: 'superman-extension',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'up',
        minAngle: 155,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.superman.extension',
        severity: 'warn',
      },
    ],
  },

  {
    id: 'burpee',
    slug: 'burpee',
    nameKey: 'exercises.burpee.name',
    descriptionKey: 'exercises.burpee.description',
    category: 'hiit',
    difficulty: 'intermediate',
    primaryMuscles: ['fullbody'],
    secondaryMuscles: ['core', 'legs', 'shoulders'],
    thumbnailEmoji: '💥',
    repLandmark: 25,
    repPhaseThreshold: { down: 80, up: 155 },
    sets: 3,
    reps: 10,
    estimatedDuration: 30,
    commonErrorKeys: [
      'exercises.burpee.errors.hips',
      'exercises.burpee.errors.jump',
      'exercises.burpee.errors.pace',
    ],
    modificationKeys: ['exercises.burpee.mods.easier', 'exercises.burpee.mods.harder'],
    rules: [
      {
        id: 'burpee-squat',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'down',
        minAngle: 60,
        maxAngle: 110,
        feedbackKey: 'workout.feedback.burpee.squat',
        severity: 'warn',
      },
      {
        id: 'burpee-body',
        landmarks: { a: 11, vertex: 23, b: 27 },
        phase: 'down',
        minAngle: 160,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.burpee.body',
        severity: 'error',
      },
    ],
  },

  {
    id: 'high-knees',
    slug: 'high-knees',
    nameKey: 'exercises.highKnees.name',
    descriptionKey: 'exercises.highKnees.description',
    category: 'cardio',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'core'],
    secondaryMuscles: ['fullbody'],
    thumbnailEmoji: '🏃',
    repLandmark: 25,
    repPhaseThreshold: { down: 150, up: 60 },
    sets: 3,
    reps: 20,
    estimatedDuration: 25,
    commonErrorKeys: [
      'exercises.highKnees.errors.height',
      'exercises.highKnees.errors.torso',
      'exercises.highKnees.errors.pace',
    ],
    modificationKeys: ['exercises.highKnees.mods.easier', 'exercises.highKnees.mods.harder'],
    rules: [
      {
        id: 'high-knees-lift',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'up',
        minAngle: 30,
        maxAngle: 90,
        feedbackKey: 'workout.feedback.highKnees.lift',
        severity: 'warn',
      },
      {
        id: 'high-knees-torso',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'any',
        minAngle: 155,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.highKnees.torso',
        severity: 'error',
      },
    ],
  },

  {
    id: 'lateral-raise',
    slug: 'lateral-raise',
    nameKey: 'exercises.lateralRaise.name',
    descriptionKey: 'exercises.lateralRaise.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['arms'],
    thumbnailEmoji: '🙆',
    repLandmark: 13,
    repPhaseThreshold: { down: 60, up: 140 },
    sets: 3,
    reps: 12,
    estimatedDuration: 35,
    commonErrorKeys: [
      'exercises.lateralRaise.errors.height',
      'exercises.lateralRaise.errors.shrug',
      'exercises.lateralRaise.errors.swing',
    ],
    modificationKeys: ['exercises.lateralRaise.mods.easier', 'exercises.lateralRaise.mods.harder'],
    rules: [
      {
        id: 'lateral-raise-height',
        landmarks: { a: 23, vertex: 11, b: 15 },
        phase: 'up',
        minAngle: 140,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.lateralRaise.height',
        severity: 'warn',
      },
    ],
  },

  {
    id: 'tricep-extension',
    slug: 'tricep-extension',
    nameKey: 'exercises.tricepExtension.name',
    descriptionKey: 'exercises.tricepExtension.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['arms'],
    secondaryMuscles: ['shoulders'],
    thumbnailEmoji: '💪',
    repLandmark: 13,
    repPhaseThreshold: { down: 85, up: 155 },
    sets: 3,
    reps: 12,
    estimatedDuration: 35,
    commonErrorKeys: [
      'exercises.tricepExtension.errors.elbow',
      'exercises.tricepExtension.errors.range',
      'exercises.tricepExtension.errors.arch',
    ],
    modificationKeys: [
      'exercises.tricepExtension.mods.easier',
      'exercises.tricepExtension.mods.harder',
    ],
    rules: [
      {
        id: 'tricep-ext-down',
        landmarks: { a: 11, vertex: 13, b: 15 },
        phase: 'down',
        minAngle: 70,
        maxAngle: 105,
        feedbackKey: 'workout.feedback.tricepExtension.elbow',
        severity: 'warn',
      },
      {
        id: 'tricep-ext-up',
        landmarks: { a: 11, vertex: 13, b: 15 },
        phase: 'up',
        minAngle: 155,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.tricepExtension.extension',
        severity: 'warn',
      },
    ],
  },

  {
    id: 'reverse-lunge',
    slug: 'reverse-lunge',
    nameKey: 'exercises.reverseLunge.name',
    descriptionKey: 'exercises.reverseLunge.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '🦶',
    repLandmark: 25,
    repPhaseThreshold: { down: 95, up: 160 },
    sets: 3,
    reps: 10,
    estimatedDuration: 40,
    commonErrorKeys: [
      'exercises.reverseLunge.errors.knee',
      'exercises.reverseLunge.errors.torso',
      'exercises.reverseLunge.errors.balance',
    ],
    modificationKeys: ['exercises.reverseLunge.mods.easier', 'exercises.reverseLunge.mods.harder'],
    rules: [
      {
        id: 'reverse-lunge-knee',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'down',
        minAngle: 80,
        maxAngle: 105,
        feedbackKey: 'workout.feedback.reverseLunge.knee',
        severity: 'warn',
      },
      {
        id: 'reverse-lunge-torso',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'any',
        minAngle: 160,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.reverseLunge.torso',
        severity: 'error',
      },
    ],
  },

  {
    id: 'wall-sit',
    slug: 'wall-sit',
    nameKey: 'exercises.wallSit.name',
    descriptionKey: 'exercises.wallSit.description',
    category: 'strength',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'glutes'],
    secondaryMuscles: ['core'],
    thumbnailEmoji: '🧱',
    repLandmark: 25,
    repPhaseThreshold: { down: 100, up: 170 },
    sets: 3,
    reps: 1,
    estimatedDuration: 60,
    commonErrorKeys: [
      'exercises.wallSit.errors.angle',
      'exercises.wallSit.errors.heels',
      'exercises.wallSit.errors.arms',
    ],
    modificationKeys: ['exercises.wallSit.mods.easier', 'exercises.wallSit.mods.harder'],
    rules: [
      {
        id: 'wall-sit-angle',
        landmarks: { a: 23, vertex: 25, b: 27 },
        phase: 'hold',
        minAngle: 82,
        maxAngle: 100,
        feedbackKey: 'workout.feedback.wallSit.angle',
        severity: 'warn',
      },
      {
        id: 'wall-sit-back',
        landmarks: { a: 11, vertex: 23, b: 25 },
        phase: 'hold',
        minAngle: 160,
        maxAngle: 185,
        feedbackKey: 'workout.feedback.wallSit.back',
        severity: 'error',
      },
    ],
  },
];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id || e.slug === id);
}
